config/routes.rb
Rails.application.routes.draw do
  
  root 'application#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_with_omniauth'

  get '/tutors/highly_rated' => 'tutors#highly_rated'

  resources :appointments, only: [:new, :create]

  resources :students do
    resources :appointments, only: [:index, :show, :edit, :update, :destroy]
  end 

  resources :tutors do
    resources :appointments, only: [:index, :show, :edit, :update, :destroy]
  end 
 
  # get '/appointments/soonest_available' => 'appointments#soonest_available - if tutors can set up availability

  get '/nacho_stuff' => 'errors#nacho_stuff'

end

app/models/student.rb
class Student < User
    has_many :appointments, dependent: :destroy
    has_many :tutors, through: :appointments
    scope :gold_stars, ->(column = :gold_stars) { order(column => :desc) }
    scope :levels, ->(column = :level) { order(column => :desc) }

    # should I incorporate this into users_table and assign upon creation?
    def url
        "/students/#{self.id}"
    end

end

app/controllers/students_controller.rb
class StudentsController < UsersController
    skip_before_action :validate_user, only: [:index]

    def index
        @students = Student.gold_stars
    end

    private

    def user_params
        params.require(:student).permit(
            :id, :type, :image, :email, :first_name, :last_name, :password, :password_confirmation,
            :about_me, :level, :gold_stars, :helicopter_parent
        )
    end

    def new_user
        user = Student.new
    end

end

app/views/students/_private.html.erb
<h1>Welcome <%= "#{current_user.full_name}!" %></h1>

<div class='users-profile'>
    <% if current_user.gold_stars %>
        <h2>Gold Stars: <%= current_user.gold_stars %></h2>
    <% end %>
    
    <h2>Current Level: <%= current_user.level %></h2>

    <h2>Your Appointments:</h2>
    <ul>
        <% current_user.appointments_by_date.each do |appt| %>
            <li><%= link_to "#{appt.tutor.full_name}: #{appt.time}", edit_student_appointment_path(current_user, appt) %></li>
        <% end %>
    </ul>

    <button><%= link_to "Create Appointment!", new_appointment_path %></button>

</div>

<br><br>

<div>
    <button><%= link_to "All Tutors", tutors_path %></button>
    <button><%= link_to "Highest Rated Tutors", '/tutors/highly_rated' %></button>
    <button><%= link_to "Edit Profile", edit_student_path(current_user) %></button>
    <button><%= link_to "Log Out", '/logout', method: 'post' %></button>
    <button><%= link_to "Home Page", '/' %></button>
</div>

app/views/students/_public.html.erb
<div class='public-profile'>
    <h1><%= public_profile.full_name %></h1>

    <h2>Level: <%= public_profile.level %></h2></h2>

    <% if public_profile.rating %>
        <h2>Gold Stars: <%= public_profile.gold_stars %></h2>
    <% end %>

    <h2>About me: <%= public_profile.about_me %></h2>

</div>

<br><br>

<div class='centered'>
    <button><%= link_to "Profile", current_user.url %></button>
    <button><%= link_to "All Students", students_path %></button>
    <button><%= link_to "Home Page", '/' %></button>
</div>

app/views/students/edit.html.erb
<%= render partial: 'partials/user_errors' %>

<img class='profile-photo' src="<%= public_profile.image %>", alt="profile pic goes here">

<%#needs a password change option%>

<%= form_with model: @user, local: true do |f| %>

    <%= f.hidden_field :type, value: "Student" %>

    <%= f.label :first_name, "First Name" %>
    <%= f.text_field :first_name %><br>

    <%= f.label :last_name, "Last Name" %>
    <%= f.text_field :last_name %><br>

    <%= f.label :email, "Email" %>
    <%= f.text_field :email %><br>
    
    <%= f.label :image, "Image Url:" %>
    <%= f.text_field :image %><br>
   
    <%= f.label :level, "Level:" %>
    <%= f.number_field :level, in: 1..100 %><br>

    <%= f.label :about_me, "Tell us a bit about yourself:" %><br>
    <%= f.text_area :about_me %><br>

    <%= f.label :helicopter_parent, "Do you have a helicopter parent? [y/n]" %>
    <%= f.check_box :helicopter_parent %><br>

    <%= f.submit "Submit Profile!" %>

<% end %>


<h3>-- OR --</h3>

<button><%= delete_profile %></button>

<br><br>

<div class='centered'>
    <button><%= link_to "Profile", current_user.url %></button>
    <button><%= link_to "All Tutors", tutors_path %></button>
    <button><%= link_to "Highest Rated Tutors", '/tutors/highly_rated' %></button>
    <button><%= link_to "Home Page", '/' %></button>
</div>

app/views/students/index.html.erb
<h1>Students ranked by gold stars - because learning can be competitve too!</h1>
<ul>
     <% @students.each do |student| %>
        <li><%= link_to "#{student.full_name} - #{student.gold_stars}", student_path(student) %></li>
    <% end %>
</ul>

<br><br>

<div class='centered'>
    <button><%= link_to "Profile", current_user.url %></button>
    <button><%= link_to "Home Page", '/' %></button>
</div>

app/views/students/new.html.erb
<h1>Create your profile! </h1>

<%= render partial: "partials/user_errors" %>

<%= form_with model: @user, local: true do |f| %>

    <%= f.hidden_field :type, value: "Student" %>

    <%= f.label :first_name, "First Name" %>
    <%= f.text_field :first_name %><br>

    <%= f.label :last_name, "Last Name" %>
    <%= f.text_field :last_name %><br>

    <%= f.label :email, "Email" %>
    <%= f.text_field :email %><br>
    
    <%= f.label :image, "Image Url:" %>
    <%= f.text_field :image %><br>
   
    <%= f.label :level, "Level:" %>
    <%= f.number_field :level, in: 1..100 %><br>

    <%= f.label :about_me, "Tell us a bit about yourself:" %><br>
    <%= f.text_area :about_me %><br>

    <%= f.label :helicopter_parent, "Do you have a helicopter parent? [y/n]" %>
    <%= f.check_box :helicopter_parent %><br>

    <%= f.label :password, "Password" %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit "Submit Profile!" %>

<% end %>


<br><br>

<div>
    <button><%= link_to "Home Page", '/' %></button>
</div>

app/views/students/stars.html.erb
<h1>Students ranked by gold stars - because learning can be competitve too!</h1>
<ul>
     <% @students.each do |student| %>
        <li><%= link_to "#{student.full_name} - #{student.gold_stars}", student_path(student) %></li>
    <% end %>
</ul>