config/routes.rb
Rails.application.routes.draw do
  
  root 'application#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_with_omniauth'

  get '/tutors/highly_rated' => 'tutors#highly_rated'

  resources :appointments, only: [:new, :create]

  resources :students do
    resources :appointments, only: [:index, :show, :edit, :update, :destroy]
  end 

  resources :tutors do
    resources :appointments, only: [:index, :show, :edit, :update, :destroy]
  end 
 
  # get '/appointments/soonest_available' => 'appointments#soonest_available - if tutors can set up availability

  get '/nacho_stuff' => 'errors#nacho_stuff'

end

app/models/tutor.rb
class Tutor < User
    has_many :appointments, dependent: :destroy
    has_many :students, through: :appointments
    scope :highly_rated, -> { where('rating > ?', 49) }
    scope :ranked_tutors, -> (column = :rating) { order(column => :desc) }

    # should I incorporate this into users_table and assign upon creation?
    def url
        "/tutors/#{self.id}"
    end

end

app/controllers/tutors_controller.rb
class TutorsController < UsersController
    skip_before_action :require_login, only: [:index, :highly_rated]
    skip_before_action :validate_user, only: [:index, :highly_rated, :search]

    def index
        @tutors = Tutor.ranked_tutors
    end

    def highly_rated
        @tutors = Tutor.highly_rated.ranked_tutors
        render :index
    end

    private

    def user_params
        params.require(:tutor).permit(
            :id, :type, :image, :email, :first_name, :last_name, :password, :password_confirmation,
            :resume, :zoom_link, :puppets, :rating
        )
    end

    def new_user
        user = Tutor.new
    end

end

app/views/tutors/_edit.html.erb
<%#= form_for(@user) do |f| %>
<%= form_with model: @user, method: 'patch', local: true do |f| %>

    <%= f.label :first_name, "First Name" %>
    <%= f.text_field :first_name %><br>

    <%= f.label :last_name, "Last Name" %>
    <%= f.text_field :last_name %><br>

    <%= f.label :email, "Email" %>
    <%= f.text_field :email %><br>
    
    <%= f.label :image, "Image Url:" %>
    <%= f.text_field :image %><br>
    
    <%= f.label :zoom_link, "Zoom Link:" %>
    <%= f.text_field :zoom_link %><br>

    <%= f.label :resume, "Resume:" %><br>
    <%= f.text_area :resume %><br>

    <%= f.label :puppets, "Puppets? [y/n]" %>
    <%= f.check_box :puppets %><br>

    <%# confirm password? %>
    
    <%= f.submit "Submit Profile!" %>

<% end %>

app/views/tutors/_private.html.erb
<h1>Welcome <%= "#{current_user.full_name}!" %></h1>

<div class='users-profile'>
    <% if current_user.rating %>
        <h3>Your Current Rating: <%= current_user.rating %></h3>
    <% end %>

    <h2>Your Appointments:</h2>
    <ul>
        <% current_user.appointments_by_date.each do |appt| %>
            <li><%= link_to "#{appt.student.full_name}: #{appt.time}", edit_tutor_appointment_path(current_user, appt) %></li>
        <% end %>
    </ul>
</div>

<br><br>

<div>
    <button class="waves-effect yellow lighten-4 btn-small"><%= link_to "All Students", students_path %></button>
    <button class="waves-effect yellow lighten-4 btn-small"><%= link_to "Edit Profile", edit_tutor_path(current_user) %></button>
    <button class="waves-effect yellow lighten-4 btn-small"><%= link_to "Log Out", '/logout', method: 'post' %></button>
    <button class="waves-effect yellow lighten-4 btn-small"><%= link_to "Home Page", '/' %></button>
</div>

app/views/tutors/_public.html.erb
<div class='public-profile'>
    <h1><%= @public_user.full_name %></h1>

    <% if @public_user.rating %>
        <h2>Current Rating: <%= @public_user.rating %></h2>
    <% end %>

    <h2>Resume: <%= @public_user.resume %></h2>

</div>

<br><br>

<div>
    <button><%= link_to "Profile", current_user.url %></button>
    <button><%= link_to "All Tutors", tutors_path %></button>
    <button><%= link_to "Home Page", '/' %></button>
</div>

app/views/tutors/edit.html.erb
<%= render partial: 'partials/user_errors' %>

<img class='profile-photo' src="<%= public_profile.image %>", alt="profile pic goes here">

<%= form_with model: @user, method: 'patch', local: true do |f| %>

    <%= f.label :first_name, "First Name" %>
    <%= f.text_field :first_name %><br>

    <%= f.label :last_name, "Last Name" %>
    <%= f.text_field :last_name %><br>

    <%= f.label :email, "Email" %>
    <%= f.text_field :email %><br>
    
    <%= f.label :image, "Image Url:" %>
    <%= f.text_field :image %><br>
    
    <%= f.label :zoom_link, "Zoom Link:" %>
    <%= f.text_field :zoom_link %><br>

    <%= f.label :resume, "Resume:" %><br>
    <%= f.text_area :resume %><br>

    <%= f.label :puppets, "Puppets? [y/n]" %>
    <%= f.check_box :puppets %><br>

    <%= f.hidden_field :category, value: "Tutor" %>
    
    <%= f.submit "Submit Profile!" %>

<% end %>

<h3>-- OR --</h3>

<button><%= delete_profile %></button>

app/views/tutors/index.html.erb
<% if params[:action] == "index" %>
    <h1>All Tutors (listed in order of rating)</h1>
<% elsif params[:action] == "highly_rated" %>
    <h1>Highly rated tutors (50+ rating)</h1>
<% end %>

<ul>
     <% @tutors.each do |tutor| %>
        <li class='tutors'>
            <%= link_to "#{tutor.full_name}", tutor_path(tutor) %>
            (rating: <%= tutor.rating %>)<br>
            <img src="<%= tutor.image %>", alt="tutor photo here">
        </li>
    <% end %>
</ul>

<br><br>

<div class='centered'>
    <button><%= link_to "Profile", current_user.url %></button>
    <button><%= link_to "Home Page", '/' %></button>
</div>

app/views/tutors/new.html.erb
<h1>Create your profile! </h1>

<%= render partial: "partials/user_errors" %>

<%= form_with model: @user, local: true do |f| %>

    <%= f.hidden_field :type, value: "Tutor" %>

    <%= f.label :first_name, "First Name" %>
    <%= f.text_field :first_name %><br>

    <%= f.label :last_name, "Last Name" %>
    <%= f.text_field :last_name %><br>

    <%= f.label :email, "Email" %>
    <%= f.text_field :email %><br>
    
    <%= f.label :image, "Image Url:" %>
    <%= f.text_field :image %><br>
    
    <%= f.label :zoom_link, "Zoom Link:" %>
    <%= f.text_field :zoom_link %><br>

    <%= f.label :resume, "Resume:" %><br>
    <%= f.text_area :resume %><br>

    <%= f.label :puppets, "Puppets? [y/n]" %>
    <%= f.check_box :puppets %><br>

    <%= f.label :password, "Password" %>
    <%= f.password_field :password %><br>

    <%= f.label :password_confirmation, "Confirm Password" %>
    <%= f.password_field :password_confirmation %><br>

    <%= f.submit "Submit Profile!" %>

<% end %>


<br><br>

<div>
    <button><%= link_to "Home Page", '/' %></button>
</div>

app/views/tutors/show.html.erb
<img class='profile-photo' src="<%= public_profile.image %>", alt="profile pic goes here">

<% if users_stuff? %>
    <%= render partial: "private" %>
<% else %>
    <%= render partial: "public" %>
<% end %>