config/routes.rb
Rails.application.routes.draw do
  
  root 'application#home'

  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  get '/auth/facebook/callback' => 'sessions#create_with_omniauth'

  get '/tutors/highly_rated' => 'tutors#highly_rated'

  resources :appointments, only: [:new, :create]

  resources :students do
    resources :appointments, only: [:index, :show, :edit, :update, :destroy]
  end 

  resources :tutors do
    resources :appointments, only: [:index, :show, :edit, :update, :destroy]
  end 
 
  # get '/appointments/soonest_available' => 'appointments#soonest_available - if tutors can set up availability

  get '/nacho_stuff' => 'errors#nacho_stuff'

end

app/views/partials/_flash.html.erb
<h3>There Be Some Problems, yo!</h3>
    <div>
        <ul>
            <% flash.each do |type, msg| %>
            <li><%= "#{type}: #{msg}" %></li>
            <% end %>
        </ul>
        <img src='/photos/sad_panda.gif'>
    </div>
<h4>Refresh the page to move on.</h4>

app/views/partials/_footer.html.erb
<div class='centered'>

  <% if !logged_in? %>
   
    <button><%= link_to "Log In", '/login' %></button>
    <button><%= link_to "Become a Tutor!", new_tutor_path %></button>
    <button><%= link_to "Become a Student!", new_student_path %></button>
    <button><%= link_to 'Log in with Facebook', '/auth/facebook' %></button>
    
    <% if !tutors_index? %>
      <button><%= link_to "Meet the Tutors!", tutors_path %></button>
    <% end %>

  <% else %>

    <% if !user_profile? %>
      <button><%= link_to "Profile", direct_to_show %></button>
    <% end %>
<%#binding.pry%>
    <% if user_profile? && current_user.is_tutor? %>
      <button><%= link_to "All Students", students_path %></button>
    <% end %>

    <% if current_user.is_student? %>
      <% if !tutors_index? %>
        <button><%= link_to "All Tutors", tutors_path %></button>
      <% end %>

      <% if !highly_rated_tutors? %>
        <button><%= link_to "Highest Rated Tutors", '/tutors/highly_rated' %></button>
      <% end %>
    <% end %>

    <% if user_profile? %>
        <button><%= link_to "Edit Profile", direct_to_edit %></button>
    <% end %>

    <button><%= link_to "Log Out", '/logout', method: 'post' %></button>

  <% end %>

  <% if params[:action] != "home" %>
    <button><%= link_to "Home Page", '/' %></button>
  <% end %>

</div>

app/views/partials/_user_errors.html.erb
<% if current_user.errors.any? %>
    <p>Errors:</p>
    <ul>
        <% current_user.errors.messages.each do |msg| %>
            <li><%= display_errors(msg) %></li>
        <% end %>
    </ul>
<% end %>
    